# -*- coding: utf-8 -*-
"""RAG_GenAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ujdV17M1dYzjxlXefNGzZBeEFrLlv1o3
"""

# Install dependencies
#!pip install PyMuPDF faiss-cpu sentence-transformers transformers fastapi uvicorn nest-asyncio -q

# Extraction from PDF file
# As suggested picking 2 chapter from PDF

import fitz
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
import faiss
import numpy as np
from transformers import pipeline

# /content/ConceptsofBiology-WEB.pdf

model = SentenceTransformer('all-MiniLM-L6-v2')
qa_pipeline = pipeline("text-generation", model="gpt2")


# load pdf and preprocesses
def extract_chapter(pdf_path, start_page, end_page):
    """Extracts text from specified pages."""
    doc = fitz.open(pdf_path)
    text = ""
    for page_num in range(start_page - 1, end_page):  # 0-indexed
        text += doc[page_num].get_text()
    return text

chapter1 = extract_chapter("ConceptsofBiology-WEB.pdf", 5, 26)
chapter2 = extract_chapter("ConceptsofBiology-WEB.pdf", 27, 54)
#full_text = chapter1 + "\n" + chapter2

#len(chapter1)

#len(chapter2)

# Chunk the text and generate embeddings


def chunk_text(text, max_tokens=250):
    #Split text into smaller chunks.
    sentences = text.split('. ')
    chunks, chunk = [], ""
    for sentence in sentences:
        if len(chunk) + len(sentence.split()) <= max_tokens:
            chunk += sentence + '. '
        else:
            chunks.append(chunk.strip())
            chunk = sentence + '. '
    if chunk:
        chunks.append(chunk.strip())
    return chunks

docs = chunk_text(chapter1) + chunk_text(chapter2)
embeddings = model.encode(docs)

#print(len(docs))
#print(len(docs[0]),len(docs[1]))

#embeddings

# Build Index using Faiss

dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(np.array(embeddings))

# Query Processing with Contextual Retrieval

def search_similar(query, top_k=3):
    #Retrieve top-k similar chunks.#
    query_embedding = model.encode([query])
    distances, indices = index.search(query_embedding, top_k)
    return [docs[i] for i in indices[0]]

#query = "What are the properties of life?"
#context_docs = search_similar(query)
#print("\n\n".join(context_docs))

# Using Huggingface LLM





def generate_answer(query):
    context = " ".join(search_similar(query))
    prompt = f"Context: {context}\n\nQuestion: {query}\nAnswer:"
    response = qa_pipeline(prompt, max_new_tokens=100, do_sample = True)
    return response[0]['generated_text']

#generate_answer("What are the properties of life?")

#generate_answer("How do cells maintain homeostasis?")

